export const INIT_APP = 'INIT_APP';

// <editor-fold desc="ARTICLES">
export const FETCH_ARTICLES_LIST_REQUEST = 'FETCH_ARTICLES_LIST_REQUEST';
export const FETCH_ARTICLES_LIST_SUCCESS = 'FETCH_ARTICLES_LIST_SUCCESS';
export const FETCH_ARTICLES_LIST_ERROR = 'FETCH_ARTICLES_LIST_ERROR';

export const FETCH_ARTICLES_ITEM_REQUEST = 'FETCH_ARTICLES_ITEM_REQUEST';
export const FETCH_ARTICLES_ITEM_SUCCESS = 'FETCH_ARTICLES_ITEM_SUCCESS';
export const FETCH_ARTICLES_ITEM_ERROR = 'FETCH_ARTICLES_ITEM_ERROR';

export const CLICK_ARTICLES_ITEM = 'CLICK_ARTICLES_ITEM';
export const CLICK_SAVE_ARTICLE_RATE = 'CLICK_SAVE_ARTICLE_RATE';
export const CLICK_LIKE_ARTICLE = 'CLICK_LIKE_ARTICLE';

export const SET_ARTICLE_RATE = 'SET_ARTICLE_RATE';
export const SET_LIKE_ARTICLE = 'SET_LIKE_ARTICLE';
// </editor-fold>

// <editor-fold desc="FIELD">
export const CHANGE_FIELD_VALUE = 'CHANGE_FIELD_VALUE';
export const RESET_FIELD_VALUE = 'RESET_FIELD_VALUE';
export const FIELD_ON_BLUR = 'FIELD_ON_BLUR';
export const FIELD_ON_FOCUS = 'FIELD_ON_FOCUS';
export const FIELD_VALIDATION_RESULT = 'FIELD_VALIDATION_RESULT';
// </editor-fold>

// <editor-fold desc="AUTH">
export const LOGIN_CLICK = 'LOGIN_CLICK';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_RESET_ERROR_TEXT = 'LOGIN_RESET_ERROR_TEXT';
export const LOGIN_FORM_VALIDATION_RESULT = 'LOGIN_FORM_VALIDATION_RESULT';

export const LOGOUT_CLICK = 'LOGOUT_CLICK';

export const AUTH_GET_STATE_REQUEST = 'AUTH_GET_STATE_REQUEST';
export const AUTH_GET_STATE_SUCCESS = 'AUTH_GET_STATE_SUCCESS';
export const AUTH_GET_STATE_ERROR = 'AUTH_GET_STATE_ERROR';
// </editor-fold>

// <editor-fold desc="REDIRECTION">
export const GO_TO_PAGE = 'GO_TO_PAGE';
export const GO_TO_ROOT = 'GO_TO_ROOT';
export const GO_TO_LOGIN = 'GO_TO_LOGIN';

export const SET_RETURN_PATH_AFTER_AUTH = 'SET_RETURN_PATH_AFTER_AUTH';
export const RESET_RETURN_PATH_AFTER_AUTH = 'RESET_RETURN_PATH_AFTER_AUTH';
// </editor-fold>
